### ISSUE TITLE
Creating form.html

### ISSUE THREAD

**Issue by ishubham21** [ishubham21/profiles-browser-extension#7]
Have to create a form in form.html to take input links to profiles from the user. 
The form should contain input fields to take - 
1. Portfolio/Website
2. Github
3. LinkedIn
4. Gmail
5. Twitter
6. StackOverflow
7. Instagram

Reference - https://codepen.io/Izaias/pen/PPJmQe

**Comment by khusboobothra** [comment]
@ishubham21 , I would like to work on this issue.
